version: "3.9"
services:
  app:
    build: .
    container_name: library
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
    ports:
      - "8080:8080"
    networks:
      - app-network
  postgres:
    image: postgres:14.9
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "543:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:


#version: "3.9"
#services:
#  app:
#    build: .
#    container_name: library
#    depends_on:
#      - postgres
#    environment:
#      DB_HOST: postgres
#    ports:
#      - "8080:8080"
#
#  postgres:
#    image: postgres:14.9
#    environment:
#      POSTGRES_DB: "postgres"
#      POSTGRES_USER: "postgres"
#      POSTGRES_PASSWORD: "postgres"
#    volumes:
#      - .:/docker-entrypoint-initdb.d
#    ports:
#      - "5432:5432"

