spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: library
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5434/postgres
    username: postgres
    password: postgres
    hikari:
      cachePrepStmts: true
      prepStmtCacheSqlLimit: 2048
      prepStmtCacheSize: 250
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

security:
  jwt:
    secret: Zndlcmd3ZXJnd2V0cmd3ZXJnd2Vxcmd3ZXJnd2VyZ3dlcmdyd2Vnd2U=
    access: 1
    refresh: 30

springdoc:
  override-with-generic-response: false
logging:
  level:
    org.apache.catalina.core.ContainerBase: off
server:
  port: 8100